#pragma config(Motor,  port1,           LMotor,        tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port5,           ClawServo,     tmotorServoStandard, openLoop)
#pragma config(Motor,  port6,           ClawMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          RMotor,        tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
	//This just sets everything to to 0.
	//motor[LMotor] = 0;
	//motor[RMotor] = 0;
	//motor[ClawMotor] = 0;
	//motor[ClawServo] = 0;

	while(true){
		if ((vexRT[Btn7L] != 0)||(vexRT[Btn8D] != 0)||(vexRT[Btn8U] != 0)||(vexRT[Btn8L] != 0)||(vexRT[Btn8R] != 0)||(vexRT[Ch4] != 0)||(vexRT[Btn5D] != 0)||(vexRT[Btn5U] != 0)||vexRT[Btn6U] != 0 || vexRT[Btn6D] != 0){

			if (vexRT[Btn8R] == 1){
				motor[LMotor] = 100;
				motor[RMotor] = 100;
			}											//This moves the bot back, press button 8R

			if (vexRT[Btn8D] == 1){
				motor[LMotor] = -80;
				motor[RMotor] = -80;
			}//This moves the bot forward, press button 8D

			if (vexRT[Btn8L] == 1){
				motor[LMotor] = 127;
				motor[RMotor] = 127;
			}
			if (vexRT[Btn8U] == 1){
				motor[LMotor] = 30;
				motor[RMotor] = 30;
			}

			if (vexRT[Ch4] > 25){
				motor[LMotor] = 75;
				motor[RMotor] = -75;
			}											//This emulates tank drive.
			if (vexRT[Ch4] < -25){		//Instead of using both joysticks, you can move channel 1 left or right.
				motor[LMotor] = -75;
				motor[RMotor] = 75;
			}

			if (vexRT[Btn5U] == 1){
				motor[ClawMotor] = 50;
			}											//This moves the claw up and down. 5U up. 5D down.
			if (vexRT[Btn5D] == 1){
				motor[ClawMotor] = -50;
			}

			if (vexRT[Btn6U] == 1){
				//motor[ClawServo] = (vexRT[Ch3] * .5);
				motor[ClawServo] = 127;
			}
			if (vexRT[Btn6D] == 1){
				//motor[ClawServo] = (vexRT[Ch3] * .5);
				motor[ClawServo] = -127;
			}//This opens and closes the claw. 6U opens. 6D closes.

			if (vexRT[Btn7L] == 1){
				motor[ClawMotor] = 0;
				motor[LMotor] = 0;
				motor[RMotor] = 0;
				motor[ClawServo] = 127;
			}
		}
		else{
			motor[ClawMotor] = 0;
			motor[LMotor] = 0;
			motor[RMotor] = 0;
		}
	}

}
